name: tinylist2
description: Class definitions for pseudo-lists that simplify working with structures commonly encountered in combinatorics such as permutations, combinations and subsets.
version: 2.0.0

homepage: https://github.com/calvintam236/tinylist2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  lint: ^1.5.3

strong-mode: true
