name: trotter
version: 1.0.1
description: Class definitions for pseudo-lists that simplify working with structures commonly encountered in combinatorics such as permutations, combinations and subsets.
author: Richard Ambler <rambler@ibwya.net.com>
homepage: https://www.bitbucket.org/ram6ler/dart_trotter/wiki/Home
environment:
  sdk: '>=2.0.0 <3.0.0'
strong-mode: true
