name: ci

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.*/**'
  pull_request:
    types:
      - ready_for_review
      - synchronize
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart
          key: ${{ github.ref }}-${{ hashFiles('pubspec.yaml') }}
      - run: dart pub get
      - run: dart analyze
      - run: dart test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart
          key: ${{ github.ref }}-${{ hashFiles('pubspec.yaml') }}
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
